Add RelationalGroupedDataFrame.pivot()
snowflakedb/snowpark-python pull request #1130
Opened 2023-11-05 23:27 UTC by sfc-gh-aalam

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #1093

2. Fill out the following pre-review checklist:

   - [x] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Added a`pivot` method in `RelationalGroupedDataFrame` which allows to access `pivot` using `df.group_by().pivot()`

2023-11-05 23:33 UTC, sfc-gh-aalam commented on src/snowflake/snowpark/relational_grouped_dataframe.py
> +            value_exprs = [Literal(v[0]) for v in distinct_values]
should we add this in `Dataframe.pivot` as well with a documentation update saying this method is not recommended?

2023-11-06 17:07 UTC, sfc-gh-sfan commented on src/snowflake/snowpark/relational_grouped_dataframe.py
> +            ... (2, 'B', 200, 'FEB') ''').collect()
I wonder if we could use `create_dataframe` then `save_as_table` to represent this `session.sql`? Maybe it is not worth it but just thinking out loud.

2023-11-06 17:07 UTC, sfc-gh-sfan commented on src/snowflake/snowpark/relational_grouped_dataframe.py
> +            )
This is actually a blocking call, and might not be cheap. I wonder if we should highlight why this is not efficient in the documentation, in addition to saying this is not recommended.

Alternatively, should we lazy evaluate this query (put them into the query plan), or at least do a async query here and fetch the result only when the value is required?

2023-11-10 17:02 UTC, sfc-gh-sfan approved these changes
Let's make sure we have a TODO for distinct values

2023-11-10 17:03 UTC, sfc-gh-sfan reviewed
Do we need to raise if `values` is `None`?

2023-11-10 18:52 UTC, sfc-gh-aalam commented
> Let's make sure we have a TODO for distinct values

https://snowflakecomputing.atlassian.net/browse/SNOW-967385

2023-11-10 18:53 UTC, sfc-gh-aalam commented
> Do we need to raise if `values` is `None`?

Right now, `df.pivot` doesn't raise it but we could raise a `ValueError` in both places saying `values cannot be empty`. Right now we get `NoneType is not iterable`

2023-11-11 00:36 UTC, sfc-gh-sfan commented
I see. Both works, probably an explicit error message is easier for user to understand :)

2023-11-16 18:45 UTC, sfc-gh-mkeller requested changes

2023-11-16 18:45 UTC, sfc-gh-mkeller commented on src/snowflake/snowpark/dataframe.py
> +            raise ValueError("values cannot be None or empty")
This should never be `None` according to the argument's type-hint
```suggestion
            raise ValueError("values cannot be empty")
```

2023-11-16 18:45 UTC, sfc-gh-mkeller commented on src/snowflake/snowpark/_internal/analyzer/analyzer.py
> +                    logical_plan.aggregates[0].children[
This is failing the `mypy` check, please fix it

2023-11-16 18:45 UTC, sfc-gh-mkeller commented on src/snowflake/snowpark/relational_grouped_dataframe.py
> +            raise ValueError("values cannot be None or empty")
Same as the other
```suggestion
            raise ValueError("values cannot be empty")
```

2023-11-16 18:45 UTC, sfc-gh-mkeller commented on src/snowflake/snowpark/relational_grouped_dataframe.py
> +        return self
You could have the return-type be [typing_extensions.Self](https://docs.python.org/3/library/typing.html#typing.Self) here

2023-11-17 17:24 UTC, sfc-gh-mkeller approved these changes
:ship: :ship:

2023-11-17 17:38 UTC, merged