SNOW-1032347: update comment of session.sql for lazy evaluation
snowflakedb/snowpark-python pull request #1249
Opened 2024-02-13 21:46 UTC by sfc-gh-aling

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #NNNN

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

2024-02-13 22:12 UTC, sfc-gh-stan commented on src/snowflake/snowpark/session.py
> +        **Note:** You can use this method to execute a SQL query, however the method is of **lazy evaluation**
```suggestion
        **Note:** You can use this method to execute a SQL query lazily,
```

2024-02-13 22:15 UTC, sfc-gh-stan commented on src/snowflake/snowpark/session.py
> +         which means the sql is not executed immediately untill :func:`DataFrame.collect` is called.
```suggestion
         which means the query is not executed until methods like :func:`DataFrame.collect` or :func:`DataFrame.to_pandas`  evaluates the DataFrame.
```

2024-02-14 00:19 UTC, sfc-gh-stan requested changes
Made two minor suggestions

2024-02-14 18:47 UTC, sfc-gh-mabrennan commented on src/snowflake/snowpark/session.py
> +         which means the sql is not executed immediately untill :func:`DataFrame.collect` is called.
sql -> SQL

2024-02-14 18:48 UTC, sfc-gh-mabrennan commented on src/snowflake/snowpark/session.py
> +         which means the sql is not executed immediately untill :func:`DataFrame.collect` is called.
evaluates -> evaluate

2024-02-14 18:48 UTC, sfc-gh-mabrennan approved these changes
lgtm

2024-02-14 20:04 UTC, sfc-gh-mabrennan commented on src/snowflake/snowpark/session.py
> +            which means the SQL is not executed untill methods like :func:`DataFrame.collect`
untill -> until

2024-02-14 20:05 UTC, sfc-gh-mabrennan commented on src/snowflake/snowpark/session.py
> +            For **immediate execution**, please chain the call with the collect method: `session.sql(query).collect()`.
remove "please".

2024-02-15 00:46 UTC, sfc-gh-stan approved these changes

2024-02-15 18:23 UTC, merged