SNOW-1043115: Add support for CONVERT_TIMEZONE to local testing.
snowflakedb/snowpark-python pull request #1299
Opened 2024-03-11 19:22 UTC by sfc-gh-jrose

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #1043115

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   This PR adds support to local testing for convert_timezone.

2024-03-12 21:38 UTC, sfc-gh-aling approved these changes

2024-03-12 22:34 UTC, sfc-gh-stan requested changes

2024-03-12 22:34 UTC, sfc-gh-stan commented on tests/integ/scala/test_function_suite.py
> +def test_convert_timezone(session, local_testing_mode):
This needs to be marked with `pytest.mark.localtest`

2024-03-13 20:02 UTC, sfc-gh-stan approved these changes

2024-03-15 01:20 UTC, merged