SNOW-1374305: Add docstring to Dataframe.merge method
snowflakedb/snowpark-python pull request #1566
Opened 2024-05-13 18:37 UTC by sfc-gh-nkumar

1. Which Jira issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   

   Fixes SNOW-1374305

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Added docstring to Dataframe.merge method

2024-05-13 19:19 UTC, sfc-gh-joshi requested changes

2024-05-13 19:19 UTC, sfc-gh-joshi commented on src/snowflake/snowpark/modin/pandas/dataframe.py
You'll need to put this docstring in modin/plugin/docstrings/dataframe.py to get it to show up. Can you also double check the built docs (`cd docs; make html; open build/html/index.html`) to make sure everything looks fine?

https://github.com/snowflakedb/snowpark-python/blob/febe20b41bfe208abc90e1de20a9ec9b60072f89/src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py#L1890-L1891

2024-05-13 19:19 UTC, sfc-gh-joshi commented on src/snowflake/snowpark/modin/pandas/dataframe.py
> +            This is not yet supported.
```suggestion
            This argument is not yet supported in Snowpark pandas.
```

2024-05-13 19:26 UTC, sfc-gh-mvashishtha approved these changes
LGTM apart from @sfc-gh-joshi 's comments

2024-05-13 20:57 UTC, sfc-gh-nkumar commented on src/snowflake/snowpark/modin/pandas/dataframe.py
Ah forgot that we have plugin for docs now. Fixed it.

2024-05-13 21:50 UTC, sfc-gh-joshi approved these changes
I see a couple of warnings when building docs https://github.com/snowflakedb/snowpark-python/actions/runs/9069683454/job/24919875813?pr=1566
```
/home/runner/work/snowpark-python/snowpark-python/src/snowflake/snowpark/modin/pandas/dataframe.py:docstring of snowflake.snowpark.modin.pandas.dataframe.DataFrame.merge:19: ERROR: Unexpected indentation.
/home/runner/work/snowpark-python/snowpark-python/src/snowflake/snowpark/modin/pandas/dataframe.py:docstring of snowflake.snowpark.modin.pandas.dataframe.DataFrame.merge:20: WARNING: Block quote ends without a blank line; unexpected unindent.
```

LGTM otherwise.

2024-05-14 22:09 UTC, sfc-gh-oplaton approved these changes

2024-05-14 23:44 UTC, merged