changes for avoiding linter errors
snowflakedb/snowpark-python pull request #2699
Opened 2024-12-02 21:04 UTC by sfc-gh-batur

1. Which Jira issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   

   Fixes SNOW-NNNNNNN

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
      - [ ] If this test skips Local Testing mode, I'm requesting review from @snowflakedb/local-testing
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency
   - [ ] If this is a new feature/behavior, I'm adding the Local Testing parity changes.
   - [ ] I acknowledge that I have ensured my changes to be thread-safe. Follow the link for more information: [Thread-safe Developer Guidelines](https://github.com/snowflakedb/snowpark-python/blob/main/CONTRIBUTING.md#thread-safe-development)

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

2024-12-02 21:48 UTC, sfc-gh-vbudati approved these changes

2024-12-02 22:25 UTC, sfc-gh-azhan requested changes

2024-12-02 22:25 UTC, sfc-gh-azhan commented on .pre-commit-config.yaml
> +        exclude: >
can we add comments to mention why we exclude them?

2024-12-03 05:28 UTC, sfc-gh-azhan approved these changes

2024-12-03 18:12 UTC, sfc-gh-batur commented on .pre-commit-config.yaml
> +        exclude: >
I have read the CLA Document and I hereby sign the CLA

2024-12-03 18:15 UTC, merged